# -*- coding: utf-8 -*-
"""phtyon_01.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HFCdcwC1AydKO2pOSJv34qd1OWSoUsPq

## 1. 사용자로부터 이름과 나이를 입력 받아 이름과 10년 후 나이를 출력하는 프로그램을 작성하시오.
---
실행 결과
```
이름: 홍길동
나이: 22
홍길동님의 10년 후 나이는 32세입니다.
```

## 2. 사용자로부터 직사각형의 가로, 세로 길이를 입력 받아 직사각형의 둘레의 길이와 넓이를 출력하는 프로그램을 작성하시오.
---
실행 결과
```
직사각형의 가로: 4
직사각형의 세로: 3
둘레의 길이: 14
넓이: 12
```
"""